### ISSUE TITLE
the problem

### ISSUE THREAD

**Issue by lofangmeng** [pkhungurn/talking-head-anime-2-demo#13]
![image](https://user-images.githubusercontent.com/75239990/126659263-7586ff4b-be2a-4c2d-a1ff-e38e83a58d7e.png)
how can i solve this problem while i am gping to go on for the first step with this
![image](https://user-images.githubusercontent.com/75239990/126659447-91743222-a926-4487-b27d-f92fe39ba5ed.png)

**Comment by dragonmeteor** [comment]
The instruction said "Change your working directory to the repository's root directory."

The "root directory" in your case is "C:\Users\ASUS\.spyder-py3\talking-head-anime-2-demo-main".
It is not "C:\Users\ASUS\.spyder-py3\talking-head-anime-2-demo-main\tha2\app".
