### ISSUE TITLE
Can’t see the output live image.

### ISSUE THREAD

**Issue by AntarcticaShinn** [pkhungurn/talking-head-anime-2-demo#17]
Yeah，this time I uploaded the image as well as the progress bars at the bottom of the ifacialmocap_puppeteer window moved as I moved  face in front of the iOS device's front-facing camera.I just can't see the live image produced.There’s nothing appeared.The output frame just had blank.In addition，my GPU is RTX3070.
![image](https://user-images.githubusercontent.com/84255253/134099733-e7968f70-640b-4085-b8e8-89c1351c4b52.png)

![image](https://user-images.githubusercontent.com/84255253/134099799-963b1ae5-018b-41c6-a4bc-5f97f6823ab1.png)
@dragonmeteor @graphemecluster excuse，can anyone help me？

**Comment by AntarcticaShinn** [comment]
In addition，my GPU is RTX3070

**Comment by AntarcticaShinn** [comment]
<img width="1064" alt="屏幕截图 2021-09-20 194203" src="https://user-images.githubusercontent.com/84255253/133996590-5fb236ce-8b90-4ca2-be60-69e8226ddf03.png">

**Comment by AntarcticaShinn** [comment]
![image](https://user-images.githubusercontent.com/84255253/134099685-0aaab261-2ec9-4226-9a99-a00db4633496.png)

**Comment by AntarcticaShinn** [comment]
# @dragonmeteor @ @dragonmeteor

**Comment by dragonmeteor** [comment]
(1) Have you unzip the model files into the tha2/data directory?
(2) Have you tried the manual_poser application? Does it work?

**Comment by AntarcticaShinn** [comment]
I forgot unzip the model files.It‘s my fault.Thanks for your patient guide.
