### ISSUE TITLE
always  flashing white

### ISSUE THREAD

**Issue by xiangcaizi113** [pkhungurn/talking-head-anime-2-demo#22]
Thank you for making such interesting software
I encountered some problems while using.
Why does my output keep flashing white and Is there any way to make the output easier to capture by obs？

**Comment by dragonmeteor** [comment]
I have updated the ifacialmocap_puppeteer to reduce flickering. Please redownload the software and see if it works for you or not. This does not reduce all the flickering: I have observed that the output image still flashes when you interact with a GUI. 

Moreover, texts (especially those before the pose parameters) always flash. I do not know how to fix this short of rewriting the software using another GUI toolkit altogether, so I do not have plans to do it.

I will not add supports for OBS or any other capturing software. You would have to modify the software yourself to better suit your needs.

**Comment by dragonmeteor** [comment]
Flickering should be eliminated by the latest update.
