### ISSUE TITLE
GPU low utilization rate

### ISSUE THREAD

**Issue by dhlolicon** [pkhungurn/talking-head-anime-2-demo#24]
Hello
I encountered some problems while using.
frames are in single digits.
GPU low utilization rate
cpu utilizationis a little higher than usual
what went wrong

**Comment by dragonmeteor** [comment]
There are several issues:

(1) Frames are in single digits.
> The network requires a lot of computational resources. A Titan RTX can only output about 10ish FPS. A user with a GTX 2090 reported only single-digit FPS. Perhaps your GPU is not powerful enough.

(2) Low GPU utilization rate.
> This is most likely because you are not measuring GPU usage the right way. See https://github.com/pkhungurn/talking-head-anime-demo/issues/10

(3) CPU utilization is a little higher than usual.
> I don't think this is a problem. The program should be doing some busy work with the GPU every frame.
