### ISSUE TITLE
possible to drive character using video without iPhone(iFacialMocap,ARKit)

### ISSUE THREAD

**Issue by xukaiquan** [pkhungurn/talking-head-anime-2-demo#27]
Thanks for the wonderful work,

I am wondering if it is possible to drive the character using the video from normal cameras.

Or can I save the blender data with using iPhone devices, and save it to a file, and later use the blender data in a Linux platform?

Thanks very much

**Comment by dragonmeteor** [comment]
It might be possible, but I don't know how to do it. You have to figure this our yourself. See #2.
