### ISSUE TITLE
Ifacialmocap alternative

### ISSUE THREAD

**Issue by thanisornsr** [pkhungurn/talking-head-anime-2-demo#28]
Hi, 

First of all super impressive work. Now come to the question. Would you mind suggesting to me if there are any alternatives to ifacialmocap in android or PC? I am thinking of using some kind of motion capture that might give the same value as the ios one and port values to your puppeteer. 

All the best,
Thanisorn

**Comment by dragonmeteor** [comment]
I don't know an alternative for PC. In fact, I tried to solve this problem myself, and I failed. See #2.

For Android, you can try [MeowFace](https://play.google.com/store/apps/details?id=com.suvidriel.meowface&hl=en&gl=US). However, I have no idea how well it works, and you have to figure out how to hook it up to the software stack yourself.

**Comment by thanisornsr** [comment]
Alright. Thank you for your answer. I will try to dig into android one and let's see if I can get something.

Cheers.

**Comment by dfmjndm** [comment]
As an alternative, maybe you can use vtube studio, which can be found on Google store and steam
