### ISSUE TITLE
Install pytorch in conda (Windows)

### ISSUE THREAD

**Issue by itemx** [pkhungurn/talking-head-anime-2-demo#32]
As the time goes by, current sample command in readme will not install a proper pytorch with cuda support.
According to pytorch's official site, the latest windows version does not support of CUDA 10.2 anymore.

Insted I tried install 11.3 as recommend (And also required for cards like 3060)

conda install pytorch torchvision cudatoolkit=11.3 -c pytorch

Then it works. I don't have git client in my recent environment so is unable to push, but I think this information can be shared in readme as well?

**Comment by dragonmeteor** [comment]
Sorry for the long silence. I've updated the README file.
