### ISSUE TITLE
Play button disapears

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [pkhungurn/talking-head-anime-2-demo#37]
When I tried to run colab.ipynb, the Play button didn't appear as introduction saying.

```
Instruction

Run the four cells below, one by one, in order by clicking the "Play" button to the left of it. Wait for each cell to finish before going to the next one.
Scroll down to the end of the last cell, and play with the GUI.
```

Please let me know how to get Play button.

**Comment by pkhungurn** [comment]
![image](https://user-images.githubusercontent.com/25254747/231179855-e1634725-f35d-4e1b-9052-d80c25c6b7f4.png)

**Comment by pkhungurn** [comment]
You might also find this instructional video useful.
https://www.youtube.com/watch?v=ZGVT7vy6oD0
