### ISSUE TITLE
Is there any way to change the Iphone part to a common pc cam?

### ISSUE THREAD

**Issue by cloisonne** [pkhungurn/talking-head-anime-2-demo#4]
I'm working on it, but if u have good idea, thank for replying.

**Comment by dragonmeteor** [comment]
Short answer: I tried. I failed. So, I don't know. See #2.

**Comment by graphemecluster** [comment]
Sorry for jumping in.
I like this short answer!
I can't make it too, so I am looking forward to your success.

**Comment by ykk648** [comment]
@graphemecluster hi there, I'm sorry to tell u that I gave up the changing-cam plan, check [CodeMiko](https://youtu.be/CsQjxEd-gsw?t=64), u will find that they even put a iPhone in front of face to catch the emotion info,hope u can get my point :)
