### ISSUE TITLE
How to transfer arkit 52 blendshapes to 37 common blendshapes in the MMD models

### ISSUE THREAD

**Issue by lith0613** [pkhungurn/talking-head-anime-2-demo#5]
Hi, thanks for your wonderful repo, I am quite interested in your convertor which can do motion transfer from facial performances.
It can transfer the 52 arkit blendshape value into MMD model 37 blendshape value. However, I am quite curious about whether there is a method which can transfer the MMD blendshapes back to arkit blendshapes? Looking forward to your reply !

**Comment by dragonmeteor** [comment]
I have never thought about the reverse problem before, so I don't know.
