### ISSUE TITLE
Connection with Unreal Iive Link Face iOS app?

### ISSUE THREAD

**Issue by krigeta** [pkhungurn/talking-head-anime-2-demo#9]
Hello, Is it possible to use the **Unreal Iive Link Face iOS app** instead of the paid app? this app can send/recieve 52 shapekeys data from the iPhone camera and then save that data as a csv, json and **Live** option is also there, is it possible to use it by using the Unreal Iive Link Face iOS app?

**Comment by dragonmeteor** [comment]
This should also be possible, and I'm not doing it either. You'd have to modify the software yourself. The source code is available, and the license should permit doing so.
